### ISSUE TITLE
Research Zenhub, create Epic for Home Page and tasks for copywriting process

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/learningequality.org-v2#15]
- [ ] Visit https://www.zenhub.com/resources or Zenhub's YouTube to learn more about Zenhub @carinediaz 
- [x] Review Khang's home page structure and then provide him with examples that were discussed in previous chat for design inspiration @carinediaz 
- [ ] Collaborate with Comms team to define a workflow for copywriting and outlining the workflow into tasks. @carinediaz 
- [ ] Create a Notion page in the parent project where the workflow definitions will live @carinediaz 
- [ ] Create a `copywriting` label in Github @carinediaz 
- [ ] Create an Epic for the home page @carinediaz 
- [ ] Create a task or tasks detailing actionable things to be done for the website home page to be published. @carinediaz
